### ISSUE TITLE
Compile warning triggerd by improper commenting in ESP32_New_TimerInterrupt.h

### ISSUE THREAD

**Issue by Hobby4life** [khoih-prog/ESP32_New_TimerInterrupt#6]
In file ESP32_New_TimerInterrupt.h

There are comments started with /* but never closed properly.
Even though they are already commented with more lines.

![image](https://user-images.githubusercontent.com/55426642/183486613-91337e94-0343-4c8f-b9f0-d10dd9ef7a12.png)

Fixed with:

![image](https://user-images.githubusercontent.com/55426642/183486114-01c4a2ac-f48d-4eb1-8a46-ca1f2e486f86.png)

**Comment by khoih-prog** [comment]
Hi @Hobby4life 

Thanks for pointing out the issue. I've already fixed similar issue last week for [**ESP32_New_ISR_Servo** library](https://github.com/khoih-prog/ESP32_New_ISR_Servo), etc., and plan to spend some time to correct this issue within this week.

Looking forward to your new contribution,

Regards,

**Comment by khoih-prog** [comment]
Hi @Hobby4life 

The [**ESP32_New_TimerInterrupt** v1.3.0](https://github.com/khoih-prog/ESP32_New_TimerInterrupt/releases/tag/v1.3.0) has just been released to fix the issue you mentioned.

Thanks and Regards,

---

### Releases v1.3.0

1. Suppress errors and warnings for new **ESP32 core v2.0.4+**
