### ISSUE TITLE
Which library should I be using?

### ISSUE THREAD

**Issue by CoryCharlton** [khoih-prog/ESP32_New_TimerInterrupt#7]
It wasn't clear if I should be using this library or [ESP32TimerInterrupt](https://github.com/khoih-prog/ESP32TimerInterrupt). They both appear to be identical at first glance (aside from versioning) and both seem to be being updated so I wasn't sure what the differences were.

Additionally I was curious why [ESP32_PWM](https://github.com/khoih-prog/ESP32_PWM) was archived. Is it no longer supported? It still shows up in the Arduino Library Manager.

Thanks for all the great work!

**Comment by khoih-prog** [comment]
Hi @CoryCharlton 

You're very welcome. Also thanks for your usage and test of the libraries.

> It wasn't clear if I should be using this library or [ESP32TimerInterrupt](https://github.com/khoih-prog/ESP32TimerInterrupt). They both appear to be identical at first glance (aside from versioning) and both seem to be being updated so I wasn't sure what the differences were.

Hereafter is the history of these ESP32 TimerInterrupt libraries

1. This [**ESP32_New_TimerInterrupt**](https://github.com/khoih-prog/ESP32_New_TimerInterrupt) was created recently to cope with the **breaking** `ESP32 core v2.0.0+`, especially for new ESP32 boards, such as `ESP32_S2, ESP32_S3, ESP32_C3`
2. The [**ESP32TimerInterrupt**](https://github.com/khoih-prog/ESP32TimerInterrupt) was originally created long ago to use with `ESP32 core v1.0.6-`, without support to new boards and breaking ESP32 core v2.0.0+. But after `ESP32_New_TimerInterrupt` library is stable, thanks to stable ESP32 v2.0.1+ core, `ESP32TimerInterrupt` has been updated to use with `ESP32 core v2.0.0+` and new boards. The catch is the library has certainly more complex and code (more difficult to manage) to deal with old core v1.0.6-.
3. You will also see [ESP32_S2_TimerInterrupt](https://github.com/khoih-prog/ESP32_S2_TimerInterrupt) and [ESP32_C3_TimerInterrupt](https://github.com/khoih-prog/ESP32_C3_TimerInterrupt) were also created to fill the gap at that tumultuous time.

So the **suggestions** are:

1. If you're only using core v2.0.0+, such as v2.0.4,  or `ESP32_S2, ESP32_S3 or ESP32_C3`, it's better to use this [**ESP32_New_TimerInterrupt**](https://github.com/khoih-prog/ESP32_New_TimerInterrupt)
2. If you're using `ESP32`, and want to be flexible to use either core v1.0.6- or v2.0.0+, use the old [**ESP32TimerInterrupt**](https://github.com/khoih-prog/ESP32TimerInterrupt) 

---

> Additionally I was curious why [ESP32_PWM](https://github.com/khoih-prog/ESP32_PWM) was archived. Is it no longer supported? It still shows up in the Arduino Library Manager.

The library has been temporarily archived, but still supported and there is no issue with Library Manager.

The **deep reasons** I recent did archive many libraries are

1. I don't have enough time to manage too many (140+) libraries at the same time
2. Some users were so rude or not spent enough time to research, and just post mundane questions. I thought it's better to archive many of them **to block unnecessary interactions and wasting my time**.
3. If sophisticated users have big issue, they will know how and where to post, such as Arduino or PIO Forum. I'll know then and will fix the libraries if bug is spotted and proven.

Regards,
